### ISSUE TITLE
Latest Xray Core Incompatibility with Marzban

### ISSUE THREAD

**Issue by johnWinchester01** [Gozargah/Marzban#1333]
**Describe the bug**
a few days ago I updated my xray core using the cli command "core-update", ever since my panel starts to freeze showing multiple failed job attempts, forcing me to restart.

**To Reproduce**
1 update xray core

**Machine details (please complete the following information):**
 - OS:  ubuntu 24
- Marzban version: latest

error logs:

marzban-1     | Execution of job "record_node_usages (trigger: interval[0:00:10], next run at: 2024-09-29 13:19:36 UTC)" skipped: maximum number of running instances reached (1)
marzban-1     | INFO:     172.71.172.152:46052 - "GET /sub/SGFzc2FuLDE3MjI5Njc3OTEPwWVNxoJ9a HTTP/1.1" 200 OK
marzban-1     | Execution of job "record_node_usages (trigger: interval[0:00:10], next run at: 2024-09-29 13:19:56 UTC)" skipped: maximum number of running instances reached (1)
marzban-1     | INFO:     172.70.242.251:29492 - "GET /api/system HTTP/1.1" 200 OK
marzban-1     | INFO:     172.70.250.139:38664 - "GET /sub/eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBYmppIiwiYWNjZXNzIjoic3Vic2NyaXB0aW9uIiwiaWF0IjoxNjk0NTQ2NjQwfQ.nTzlF-I5R_GZMt3rF2jR8PgRcVj57yyjDzebKPBlRGM HTTP/1.1" 200 OK
marzban-1     | INFO:     162.158.87.86:13808 - "GET /api/system HTTP/1.1" 200 OK
marzban-1     | INFO:     162.158.87.85:9272 - "GET /api/system HTTP/1.1" 200 OK
marzban-1     | WARNING:  Restarting Xray core...
marzban-1     | WARNING:  Xray core stopped
marzban-1     | WARNING:  Xray core 24.9.19 started
marzban-1     | INFO:     162.158.87.85:9272 - "PUT /api/core/config HTTP/1.1" 200 OK
marzban-1     | Execution of job "record_node_usages (trigger: interval[0:00:10], next run at: 2024-09-29 13:20:16 UTC)" skipped: maximum number of running instances reached (1)
marzban-1     | INFO:     162.158.87.85:9272 - "GET /api/system HTTP/1.1" 200 OK
marzban-1     | INFO:     connection closed
marzban-1     | Execution of job "record_user_usages (trigger: interval[0:00:30], next run at: 2024-09-29 13:20:36 UTC)" skipped: maximum number of running instances reached (1)
marzban-1     | Execution of job "record_node_usages (trigger: interval[0:00:10], next run at: 2024-09-29 13:20:36 UTC)" skipped: maximum number of running instances reached (1)
marzban-1     | Execution of job "record_node_usages (trigger: interval[0:00:10], next run at: 2024-09-29 13:20:56 UTC)" skipped: maximum number of running instances reached (1)

**Comment by ImMohammad20000** [comment]
i'll remove all legacy code 

> New Xray versions removed some old features(like QUIC transport), if you have them then remove them from your server config or check Xray logs to debug it yourself

i'll remove all legacy code later

**Comment by M03ED** [comment]
> > New Xray versions removed some old features(like QUIC transport), if you have them then remove them from your server config or check Xray logs to debug it yourself
> 
> i'll remove all legacy code later

quic transport must remain in code for compatibility with lower xray versions

**Comment by johnWinchester01** [comment]
> New Xray versions removed some old features(like QUIC transport), if you have them then remove them from your server config
> or check Xray logs to debug it yourself

no i don't have any quic inbounds

**Comment by M03ED** [comment]
> > New Xray versions removed some old features(like QUIC transport), if you have them then remove them from your server config
> > or check Xray logs to debug it yourself
> 
> no i don't have any quic inbounds

Send xray logs

**Comment by H-Alireza** [comment]
I got same problem 
All I get it marzban log is this: 
marzban-1     | Execution of job "record_node_usages (trigger: interval[0:00:10], next run at: 2024-10-22 16:06:52 UTC)" skipped: maximum number of running instances reached (1)

and my master server configs get unavailable and give handshake error
after I restart marzban it get fixed

**Comment by zoomerland** [comment]
This may explain one failure mode behind the symptoms reported here.

In the current Marzban process launcher, Xray is started with separate stdout and stderr pipes, but only stdout is drained. If enough runtime/error output is written to stderr, that pipe fills and Xray blocks. In our affected instance, a goroutine profile showed the net/http error logger blocked in `write(fd=2)`, while scheduled jobs and connections subsequently stalled.

A minimal fix and regression tests are available in #2092.

In a same-duration 21.3-hour production comparison after applying the patch:
- Xray stayed on one PID with no guard restarts or warnings;
- `CLOSE_WAIT` p95 decreased from 95 to 14, maximum from 147 to 25;
- FD p95 decreased from 501 to 175;
- current `CLOSE_WAIT` was 0 and FD count was 22.

A transient FD spike recovered normally, instead of accumulating. This does not prove that every report in this issue has the same root cause, but it provides a reproducible failure mechanism and production evidence for this particular one.

**Comment by zoomerland** [comment]
Follow-up to the earlier report: the fix in #2092 has now completed 71.2 hours of production observation, with 4,121 valid one-minute samples across three Xray process cycles and two scheduled host reboots.

Compared with the pre-fix baseline:

- no resource-guard warnings, unscheduled Xray restarts, OOM events, or critical Marzban log patterns occurred;
- `CLOSE_WAIT` median decreased from 10 to 0, p95 from 95 to 12, and maximum from 147 to 31;
- FD p95 decreased from 501 to 174;
- each Xray process remained healthy for roughly 23.4-23.9 hours until the next scheduled host reboot;
- a transient FD peak recovered normally instead of accumulating.

At the latest check, the panel returned HTTP 200, proxy ports were listening, `CLOSE_WAIT` was 0, and stdout/stderr still shared the same actively drained pipe. This strengthens the evidence that the unread stderr pipe was the cause of our observed failure mode, while still not implying that every outage reported in this issue necessarily had the same cause.
